import { createProject } from '~~/server/db'
import { nanoid } from 'nanoid'

const CLAW_GUIDE_TEMPLATE = `# ClawDocu — AI Agent Guide

This file helps AI agents (CLAWs) understand how to work with ClawDocu comments.

## What is ClawDocu?

ClawDocu stores inline code comments in \`.clawdocu-comments/\` folder, synced with GitHub.

## How CLAWs Should Use This

### 1. Read metadata.json

When working on this repo, first read \`.clawdocu-comments/metadata.json\`:

\`\`\`json
{
  "projectId": "abc123",
  "clawdocuUrl": "https://clawdocu.example.com",
  "createdAt": "2026-05-07T00:00:00Z"
}
\`\`\`

### 2. Construct Share Links

When discussing code with your human, send ClawDocu links:

\`\`\`
{clawdocuUrl}/project/{projectId}/{filePath}
\`\`\`

Example:
\`\`\`
https://clawdocu.example.com/project/abc123/src/index.ts
\`\`\`

### 3. When to Send Links

Send the link to your human when:
- You edit a file
- You add comments
- You discuss specific code

### 4. Read and Reply to Comments

Comments are stored in \`.clawdocu-comments/comments.json\`. Read this file to see what your human wants you to look at.

**Comment structure:**

\`\`\`json
{
  "files": [
    {
      "path": "src/index.ts",
      "comments": [
        {
          "id": "1700000000000",
          "lineNumber": 42,
          "selectedText": "function parse()",
          "text": "Can you refactor this to use async/await?",
          "createdAt": "2026-07-15T10:00:00Z",
          "followups": [
            {
              "id": "1700000000001",
              "author": "agent",
              "body": "Done! Switched to async/await in commit abc123.",
              "createdAt": "2026-07-15T10:05:00Z"
            }
          ]
        }
      ]
    }
  ]
}
\`\`\`

**Fields:**
- \`id\` — Unique identifier (timestamp-based)
- \`lineNumber\` — Line number in the file where the comment is pinned
- \`selectedText\` — The code snippet that was highlighted
- \`text\` — The comment text from your human
- \`followups\` — Threaded replies (optional, only present if there are replies)

**How to reply:**

To reply to a comment, append a followup object to the comment's \`followups\` array:

\`\`\`json
{
  "id": "<timestamp>",
  "author": "agent",
  "body": "Your reply here",
  "createdAt": "<ISO timestamp>"
}
\`\`\`

- \`author\` must be \`"agent"\` for CLAW replies (human replies use \`"user"\`)
- If the \`followups\` array doesn't exist yet, create it: \`"followups": []\`
- After editing, the file will sync to the ClawDocu UI automatically

**Tips:**
- Always read comments before making changes — your human may have left instructions on specific lines
- Reply to comments when you've addressed them, so your human knows it's done
- You can also leave comments proactively by adding new comment objects to the relevant file's array

## File Structure

\`\`\`
.clawdocu-comments/
├── claw-guide.md     # This file - guide for AI agents
├── metadata.json     # Project ID and ClawDocu URL
└── comments.json     # All comments as a single JSON file
\`\`\`

---

*Generated by [ClawDocu](https://github.com/clawish/clawdocu)*
`

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const { fullName } = body
  
  // Block adding ClawDocu repo itself to avoid self-referential comments
  if (fullName.toLowerCase() === 'clawish/clawdocu') {
    throw createError({
      statusCode: 400,
      message: 'Cannot add ClawDocu repository itself as a project'
    })
  }
  
  // Get repo info from GitHub
  const config = useRuntimeConfig()
  const token = config.githubToken || process.env.GITHUB_TOKEN
  const clawdocuUrl = config.public?.clawdocuUrl || process.env.CLAWDOCU_URL || 'https://clawdocu.example.com'
  
  if (!token) {
    throw createError({
      statusCode: 500,
      message: 'GITHUB_TOKEN not configured'
    })
  }
  
  const res = await fetch(`https://api.github.com/repos/${fullName}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json'
    }
  })
  
  if (!res.ok) {
    throw createError({
      statusCode: 400,
      message: 'Repository not found or not accessible'
    })
  }
  
  const repo = await res.json()
  
  // Generate projectId
  const projectId = nanoid()
  
  // Create project in database with custom ID
  await createProject({
    id: projectId,
    name: repo.name,
    fullName: repo.full_name,
    description: repo.description,
  })
  
  // Create metadata.json
  const metadata = {
    projectId,
    clawdocuUrl,
    createdAt: new Date().toISOString()
  }
  const metadataContent = JSON.stringify(metadata, null, 2)
  
  // Create claw-guide.md with actual values
  const clawGuideContent = CLAW_GUIDE_TEMPLATE
    .replace(/{{CLAWDOCU_URL}}/g, clawdocuUrl)
    .replace(/{{PROJECT_ID}}/g, projectId)
  
  const owner = fullName.split('/')[0]
  const repoName = fullName.split('/')[1]
  
  try {
    // Create metadata.json
    const metadataEncoded = Buffer.from(metadataContent).toString('base64')
    await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/.clawdocu-comments/metadata.json`,
      {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: 'Add ClawDocu metadata for sharing',
          content: metadataEncoded
        })
      }
    )
    
    // Create claw-guide.md
    const clawGuideEncoded = Buffer.from(clawGuideContent).toString('base64')
    await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/contents/.clawdocu-comments/claw-guide.md`,
      {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: 'Add ClawDocu guide for CLAWs',
          content: clawGuideEncoded
        })
      }
    )
  } catch (e) {
    // Non-critical — don't fail project creation if seeding fails
    console.error('Failed to create .clawdocu-comments files:', e)
  }
  
  return { success: true, projectId }
})